# import phase 3 container
FROM callahantiff/pheknowlator:latest

#COPY *.py *.txt /PheKnowLator/builds/
#
#WORKDIR /PheKnowLator/builds/
#RUN pip install -r build_requirements.txt
#
#ENTRYPOINT ["python", "build_phase_3.py"]
ENTRYPOINT ["echo", "hello world"]