#!/usr/local/bin/docker
# -*- version: 20.10.2 -*-

# import phase 3 container
FROM callahantiff/pheknowlator:latest

# allow statements and log messages to immediately appear in logs
ENV PYTHONUNBUFFERED True

# set working directory in container
WORKDIR /PheKnowLator/

# download build dependencies and move them to the correct location
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/edge_source_list.txt && mv edge_source_list.txt resources/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/ontology_source_list.txt && mv ontology_source_list.txt resources/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/resource_info.txt && mv resource_info.txt resources/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/subclass_construction_map.pkl && mv subclass_construction_map.pkl resources/construction_approach/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/PheKnowLator_MergedOntologies.owl && mv PheKnowLator_MergedOntologies.owl resources/knowledge_graphs/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/node_metadata_dict.pkl && mv node_metadata_dict.pkl resources/node_data/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/INVERSE_RELATIONS.txt && mv INVERSE_RELATIONS.txt resources/relations_data/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/RELATIONS_LABELS.txt && mv RELATIONS_LABELS.txt resources/relations_data/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/DISEASE_MONDO_MAP.txt && mv DISEASE_MONDO_MAP.txt resources/processed_data/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/ENSEMBL_GENE_ENTREZ_GENE_MAP.txt && mv ENSEMBL_GENE_ENTREZ_GENE_MAP.txt resources/processed_data/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/ENTREZ_GENE_PRO_ONTOLOGY_MAP.txt && mv ENTREZ_GENE_PRO_ONTOLOGY_MAP.txt resources/processed_data/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/GENE_SYMBOL_ENSEMBL_TRANSCRIPT_MAP.txt && mv GENE_SYMBOL_ENSEMBL_TRANSCRIPT_MAP.txt resources/processed_data/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/ENTREZ_GENE_ENSEMBL_TRANSCRIPT_MAP.txt && mv ENTREZ_GENE_ENSEMBL_TRANSCRIPT_MAP.txt resources/processed_data/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/HPA_GTEx_TISSUE_CELL_MAP.txt && mv HPA_GTEx_TISSUE_CELL_MAP.txt resources/processed_data/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/MESH_CHEBI_MAP.txt && mv MESH_CHEBI_MAP.txt resources/processed_data/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/PHENOTYPE_HPO_MAP.txt && mv PHENOTYPE_HPO_MAP.txt resources/processed_data/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/STRING_PRO_ONTOLOGY_MAP.txt && mv STRING_PRO_ONTOLOGY_MAP.txt resources/processed_data/
RUN curl -O https://storage.googleapis.com/pheknowlator/temp_build_inprogress/data/processed_data/UNIPROT_ACCESSION_PRO_ONTOLOGY_MAP.txt && mv UNIPROT_ACCESSION_PRO_ONTOLOGY_MAP.txt resources/processed_data/

# copying local scripts to container
COPY build_phase_3.py /PheKnowLator/
COPY phase3_log_daemon.py build_utilities.py build_requirements.txt logging.ini /PheKnowLator/builds/
COPY logging.ini /PheKnowLator/pkt_kg

# install requirements
RUN pip install -r builds/build_requirements.txt

# set OWlTools memory (set to a high value, system will only use available memory)
ENV OWLTOOLS_MEMORY=100g
RUN echo $OWLTOOLS_MEMORY

# set working directory and python path
WORKDIR /PheKnowLator/
ENV PYTHONPATH='.'

# run script
ARG app_arg
ENV app=$app_arg
ARG rel_arg
ENV rel=$rel_arg
ARG owl_arg
ENV owl=$owl_arg

ENTRYPOINT exec python build_phase_3.py --app $app --rel $rel --owl $owl
