name: KG Build - Part 2 (Construct Knowledge Graphs)
on:
 schedule:
   - cron: '0 0 29 * *'  # runs at 00:00:00 UTC on the second day of each month
env:
 PROJECT_ID: ${{ secrets.GCE_PROJECT }}
 GCS_SERVICE_ACCOUNT: ${{ secrets.GCE_SA_KEY }}

jobs:
 pkt-build-phase3-job1:
   name: KG Build Phase 3 - Job 1 (Subclass + RelationsOnly + OWL/OWL-NETS)
   runs-on: ubuntu-latest
   timeout-minutes: 3000
   env:
     GCE_ZONE: us-central1-a
     GCE_CPU: 4
     GCE_MEMORY: 200GB
     GCE_BOOT_DISC_TYPE: pd-standard
     GCE_BOOT_DISC_SIZE: 150GB
     DOCKERFILE: builds/Dockerfile.phase3
     GCE_JOB_NAME: pkt-builder-phase3-job1
     GCS_LOCATION: 'subclass_builds/relations_only/owl'
     KG_CONSTRUCT_APPROACH: 'subclass'
     INV_RELATIONS: 'no'
     DECODE_OWL: 'yes'
   steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         ref: master
     - name: Setup Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.6
     - name: Install Requirements and Dependencies
       run: pip install -r builds/build_requirements.txt pkt_kg
     - uses: google-github-actions/setup-gcloud@master
       with:
         version: '290.0.1'
         service_account_key: ${{ secrets.GCE_SA_KEY }}
         project_id: ${{ secrets.GCE_PROJECT }}
     - name: Configure Docker Authentication
       run: gcloud --quiet auth configure-docker
     - name: Build Docker Image
       run: |-
           docker build --tag "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA" -f "$DOCKERFILE" ./builds \
           --build-arg "app_arg=$KG_CONSTRUCT_APPROACH" --build-arg "rel_arg=$INV_RELATIONS" --build-arg "owl_arg=$DECODE_OWL"
     - name: Publish Docker Image to Google Container Registry
       run: docker push "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA"
     - name: Create Virtual Machine Instance
       run: |-
           gcloud compute instances create-with-container "$GCE_JOB_NAME" --zone="$GCE_ZONE" \
           --container-image "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA" --container-restart-policy=never \
           --boot-disk-type="$GCE_BOOT_DISC_TYPE" --boot-disk-size="$GCE_BOOT_DISC_SIZE" \
           --custom-cpu="$GCE_CPU" --custom-memory="$GCE_MEMORY" --custom-extensions --scopes=storage-rw
     - name: Monitor Build
       run: python builds/job_monitoring.py --gce_type reg --phase 3 --sleep 60 --gcs_dir "$GCS_LOCATION" --project '' --job ''
#       - name: Stop Virtual Machine Instance
#         run: gcloud compute instances stop "$GCE_JOB_NAME" --zone="$GCE_ZONE"
#       - name: Delete Virtual Machine Instance
#         run: gcloud compute instances delete "$GCE_JOB_NAME" --zone="$GCE_ZONE"

 pkt-build-phase3-job2:
#    needs: pkt-build-phase-1-2
   name: KG Build Phase 3 - Job 2 (Subclass + InverseRelations + OWL/OWL-NETS)
   runs-on: ubuntu-latest
   timeout-minutes: 3000
   env:
     GCE_ZONE: us-west1-b
     GCE_CPU: 8
     GCE_MEMORY: 200GB
     GCE_BOOT_DISC_TYPE: pd-standard
     GCE_BOOT_DISC_SIZE: 150GB
     DOCKERFILE: builds/Dockerfile.phase3
     GCE_JOB_NAME: pkt-builder-phase3-job2
     GCS_LOCATION: 'subclass_builds/inverse_relations/owl'
     KG_CONSTRUCT_APPROACH: 'subclass'
     INV_RELATIONS: 'yes'
     DECODE_OWL: 'yes'
   steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         ref: master
     - name: Setup Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.6
     - name: Install Requirements and Dependencies
       run: pip install -r builds/build_requirements.txt pkt_kg
     - uses: google-github-actions/setup-gcloud@master
       with:
         version: '290.0.1'
         service_account_key: ${{ secrets.GCE_SA_KEY }}
         project_id: ${{ secrets.GCE_PROJECT }}
     - name: Configure Docker Authentication
       run: gcloud --quiet auth configure-docker
     - name: Build Docker Image
       run: |-
           docker build --tag "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA" -f "$DOCKERFILE" ./builds \
           --build-arg "app_arg=$KG_CONSTRUCT_APPROACH" --build-arg "rel_arg=$INV_RELATIONS" --build-arg "owl_arg=$DECODE_OWL"
     - name: Publish Docker Image to Google Container Registry
       run: docker push "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA"
     - name: Create Virtual Machine Instance
       run: |-
           gcloud compute instances create-with-container "$GCE_JOB_NAME" --zone="$GCE_ZONE" \
           --container-image "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA" --container-restart-policy=never \
           --boot-disk-type="$GCE_BOOT_DISC_TYPE" --boot-disk-size="$GCE_BOOT_DISC_SIZE" \
           --custom-cpu="$GCE_CPU" --custom-memory="$GCE_MEMORY" --custom-extensions --scopes=storage-rw
     - name: Monitor Build
       run: python builds/job_monitoring.py --gce_type reg --phase 3 --sleep 60 --gcs_dir "$GCS_LOCATION" --project '' --job ''
#       - name: Stop Virtual Machine Instance
#         run: |
#           gcloud compute scp --zone="$GCE_ZONE" --project="$PROJECT_ID" "$GCE_JOB_NAME:system_stats.txt" system_stats.txt |\
#           gsutil cp system_stats.txt gs://pheknowlator/temp_build_inprogress/knowledge_graphs/$GCS_LOCATION
#           gcloud compute instances stop "$GCE_JOB_NAME" --zone="$GCE_ZONE"
#       - name: Delete Virtual Machine Instance
#         run: gcloud compute instances delete "$GCE_JOB_NAME" --zone="$GCE_ZONE"

 pkt-build-phase3-job3:
#    needs: pkt-build-phase-1-2
   name: KG Build Phase 3 - Job 3 (Instance + RelationsOnly + OWL/OWL-NETS)
   runs-on: ubuntu-latest
   timeout-minutes: 3000
   env:
     GCE_ZONE: us-central1-a
     GCE_CPU: 4
     GCE_MEMORY: 200GB
     GCE_BOOT_DISC_TYPE: pd-standard
     GCE_BOOT_DISC_SIZE: 150GB
     DOCKERFILE: builds/Dockerfile.phase3
     GCE_JOB_NAME: pkt-builder-phase3-job3
     GCS_LOCATION: 'instance_builds/relations_only/owl'
     KG_CONSTRUCT_APPROACH: 'instance'
     INV_RELATIONS: 'no'
     DECODE_OWL: 'yes'
   steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         ref: master
     - name: Setup Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.6
     - name: Install Requirements and Dependencies
       run: pip install -r builds/build_requirements.txt pkt_kg
     - uses: google-github-actions/setup-gcloud@master
       with:
         version: '290.0.1'
         service_account_key: ${{ secrets.GCE_SA_KEY }}
         project_id: ${{ secrets.GCE_PROJECT }}
     - name: Configure Docker Authentication
       run: gcloud --quiet auth configure-docker
     - name: Build Docker Image
       run: |-
           docker build --tag "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA" -f "$DOCKERFILE" ./builds \
           --build-arg "app_arg=$KG_CONSTRUCT_APPROACH" --build-arg "rel_arg=$INV_RELATIONS" --build-arg "owl_arg=$DECODE_OWL"
     - name: Publish Docker Image to Google Container Registry
       run: docker push "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA"
     - name: Create Virtual Machine Instance
       run: |-
          gcloud compute instances create-with-container "$GCE_JOB_NAME" --zone="$GCE_ZONE" \
          --container-image "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA" --container-restart-policy=never \
          --boot-disk-type="$GCE_BOOT_DISC_TYPE" --boot-disk-size="$GCE_BOOT_DISC_SIZE" \
          --custom-cpu="$GCE_CPU" --custom-memory="$GCE_MEMORY" --custom-extensions --scopes=storage-rw
     - name: Monitor Build
       run: python builds/job_monitoring.py --gce_type reg --phase 3 --sleep 60 --gcs_dir "$GCS_LOCATION" --project '' --job ''
#       - name: Stop Virtual Machine Instance
#         run: gcloud compute instances stop "$GCE_JOB_NAME" --zone="$GCE_ZONE"
#       - name: Delete Virtual Machine Instance
#         run: gcloud compute instances delete "$GCE_JOB_NAME" --zone="$GCE_ZONE"

 pkt-build-phase3-job4:
#    needs: pkt-build-phase-1-2
   name: KG Build Phase 3 - Job 4 (Instance + InverseRelations + OWL/OWL-NETS)
   runs-on: ubuntu-latest
   timeout-minutes: 3000
   env:
     GCE_ZONE: us-central1-a
     GCE_CPU: 8
     GCE_MEMORY: 200GB
     GCE_BOOT_DISC_TYPE: pd-standard
     GCE_BOOT_DISC_SIZE: 150GB
     DOCKERFILE: builds/Dockerfile.phase3
     GCE_JOB_NAME: pkt-builder-phase3-job4
     GCS_LOCATION: 'instance_builds/inverse_relations/owl'
     KG_CONSTRUCT_APPROACH: 'instance'
     INV_RELATIONS: 'yes'
     DECODE_OWL: 'yes'
   steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
        ref: master
     - name: Setup Python
       uses: actions/setup-python@v2
       with:
        python-version: 3.6
     - name: Install Requirements and Dependencies
       run: pip install -r builds/build_requirements.txt pkt_kg
     - uses: google-github-actions/setup-gcloud@master
       with:
         version: '290.0.1'
         service_account_key: ${{ secrets.GCE_SA_KEY }}
         project_id: ${{ secrets.GCE_PROJECT }}
     - name: Configure Docker Authentication
       run: gcloud --quiet auth configure-docker
     - name: Build Docker Image
       run: |-
           docker build --tag "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA" -f "$DOCKERFILE" ./builds \
           --build-arg "app_arg=$KG_CONSTRUCT_APPROACH" --build-arg "rel_arg=$INV_RELATIONS" --build-arg "owl_arg=$DECODE_OWL"
     - name: Publish Docker Image to Google Container Registry
       run: docker push "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA"
     - name: Create Virtual Machine Instance
       run: |-
           gcloud compute instances create-with-container "$GCE_JOB_NAME" --zone="$GCE_ZONE" \
           --container-image "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA" --container-restart-policy=never \
           --boot-disk-type="$GCE_BOOT_DISC_TYPE" --boot-disk-size="$GCE_BOOT_DISC_SIZE" \
           --custom-cpu="$GCE_CPU" --custom-memory="$GCE_MEMORY" --custom-extensions --scopes=storage-rw
     - name: Monitor Build
       run: python builds/job_monitoring.py --gce_type reg --phase 3 --sleep 60 --gcs_dir "$GCS_LOCATION" --project '' --job ''
#       - name: Stop Virtual Machine Instance
#         run: gcloud compute instances stop "$GCE_JOB_NAME" --zone="$GCE_ZONE"
#       - name: Delete Virtual Machine Instance
#         run: gcloud compute instances delete "$GCE_JOB_NAME" --zone="$GCE_ZONE"

#TODO: consider adding the code to remove the tempbuild_inprogress directory to the builds phase 3 script
#  build-clean-up:
#    needs: [pkt-build-phase3-job1, pkt-build-phase3-job2, pkt-build-phase3-job3, pkt-build-phase3-job4]
#    name: KG Build Clean-Up
#    runs-on: ubuntu-latest
#    steps:
#      - uses: google-github-actions/setup-gcloud@master
#        with:
#          version: '290.0.1'
#          service_account_key: ${{ secrets.GCE_SA_KEY }}
#          project_id: ${{ secrets.GCE_PROJECT }}
#      - name: Delete temp_build_inprogress
#        run: gsutil rm -r gs://pheknowlator/temp_build_inprogress

#TODO: Uncomment all code once Terraform solution is implemented
# fix Bill's endpoint code to update for new builds (place that chunk before the build-clean-up section)
# need self-hosted runners or Terraform: https://github.com/terraform-google-modules/terraform-google-github-actions-runners/blob/master/examples/gh-runner-gke-dind/README.md
